token:
    expiration_time: 864000000
    secret: '{cipher}AQBSTibIkDoa4vgGNtMfiTI660f+Uj7m2gDVPCG+rH13VFlnpWmEmnoZtK9Ih3NHYr3yJZuo6PCENNuwP2+oAAC2uMwnO/NPzq0HRbOMIkAY570w9x0ZS7NMiRAKJ4u3l6cSI2dAXzYhWSbBcVEiIrMdlL5kuL8ZOXUIAcheEkaKiWk1UTAEH3+russ6yvSHjqBKbW1y1Ofd085X/9wdccT++WnkCu3i4B5zy2MiGKFAWAXdKlQB+yKPqvwKH69tGSTehH1ZJ7/xaUCS2poWbDHrgVXM4SiHhdkQejAZY9Ai+boQgu5VuDUY3jl/kW9H2L0Gl5oBTjNQ43QfquRnnAjdNcWui2IP8OgueKS79yGH5gzhxHnV/gYdFPpn11jhAFA29lr97PAjXzEvZY2ywnhm'
#user_token_defult

gateway:
    ip: 0.0.0.0